import type { Locale } from "./i18n";

type FormText = Record<string,string> & {steps:string[]};
const common = {
  tr:{steps:["Mülk","Durum","İletişim"],area:"Bölge / mahalle *",type:"Mülk tipi *",size:"Yaklaşık büyüklük *",parcel:"Ada / parsel",price:"Fiyat beklentisi",title:"Tapu durumu *",zoning:"İmar durumu",timing:"Satış zamanı *",decision:"Karar durumu *",name:"Ad soyad *",phone:"Telefon / WhatsApp *",note:"Ek bilgi",choose:"Seçin",next:"Devam",back:"Geri",submit:"Ön değerlendirme iste",sending:"Gönderiliyor…",consent:"KVKK / gizlilik bilgisini okudum.",fine:"Başvuru satış zorunluluğu veya satın alma taahhüdü oluşturmaz.",success:"Teşekkürler. Dosyanızı inceleyip uygunluk varsa sizinle iletişime geçeceğiz."},
  de:{steps:["Objekt","Situation","Kontakt"],area:"Region / Ort *",type:"Objektart *",size:"Ungefähre Größe *",parcel:"Ada / Parsel",price:"Preisvorstellung",title:"Eigentumsstatus *",zoning:"Baurecht / Planung",timing:"Verkaufszeitraum *",decision:"Entscheidung *",name:"Name *",phone:"Telefon / WhatsApp *",note:"Zusatzinfo",choose:"Bitte wählen",next:"Weiter",back:"Zurück",submit:"Prüfung anfragen",sending:"Wird gesendet…",consent:"Ich habe die Datenschutzinformation gelesen.",fine:"Die Anfrage verpflichtet weder zum Verkauf noch zum Kauf.",success:"Danke. Wir prüfen die Angaben und melden uns bei möglicher Passung."},
  en:{steps:["Property","Situation","Contact"],area:"Area / neighbourhood *",type:"Property type *",size:"Approx. size *",parcel:"Block / parcel",price:"Asking price",title:"Title status *",zoning:"Zoning",timing:"Selling timeline *",decision:"Decision status *",name:"Name *",phone:"Phone / WhatsApp *",note:"Additional info",choose:"Choose",next:"Continue",back:"Back",submit:"Request review",sending:"Sending…",consent:"I have read the privacy notice.",fine:"The enquiry creates no obligation to sell or purchase.",success:"Thank you. We will review the property and contact you if relevant."},
  ru:{steps:["Объект","Ситуация","Контакт"],area:"Район *",type:"Тип объекта *",size:"Примерная площадь *",parcel:"Ada / Parsel",price:"Желаемая цена",title:"Статус Tapu *",zoning:"Зонирование",timing:"Срок продажи *",decision:"Решение собственников *",name:"Имя *",phone:"Телефон / WhatsApp *",note:"Дополнительно",choose:"Выберите",next:"Далее",back:"Назад",submit:"Запросить оценку",sending:"Отправка…",consent:"Я прочитал(а) информацию о конфиденциальности.",fine:"Заявка не обязывает к продаже или покупке.",success:"Спасибо. Мы рассмотрим объект и свяжемся при наличии интереса."},
  ar:{steps:["العقار","الوضع","التواصل"],area:"المنطقة *",type:"نوع العقار *",size:"المساحة التقريبية *",parcel:"Ada / Parsel",price:"السعر المتوقع",title:"وضع سند الملكية *",zoning:"التنظيم",timing:"موعد البيع *",decision:"وضع القرار *",name:"الاسم *",phone:"الهاتف / واتساب *",note:"معلومات إضافية",choose:"اختر",next:"متابعة",back:"رجوع",submit:"اطلب التقييم",sending:"جارٍ الإرسال…",consent:"قرأت إشعار الخصوصية.",fine:"الطلب لا يلزمك بالبيع ولا يشكل التزاماً بالشراء.",success:"شكراً. سنراجع العقار ونتواصل معك إذا كان مناسباً."}
} satisfies Record<Locale,FormText>;
export const formCopy = common;

const labels = {
  tr:{land:"Arsa / Tarla / Bahçe",building:"Bina",villa:"Müstakil ev / Villa",flat:"Daire",commercial:"Dükkan / Ticari",other:"Diğer",single:"Müstakil tapu",condo:"Kat mülkiyeti / kat irtifakı",shared:"Hisseli tapu",transfer:"Tapu / intikal süreci devam ediyor",unknown:"Bilmiyorum",zoned:"İmarlı",unzoned:"Tarla / imarsız",plan:"Plan / dönüşüm sürecinde",soon:"Teklif uygunsa hemen",month:"7-30 gün",quarter:"1-3 ay",later:"3+ ay",sole:"Tek malikim ve karar verebilirim",joint:"Diğer maliklerle birlikte karar verebiliriz",nojoint:"Hissedarıyım, henüz ortak karar yok",inherit:"Miras / intikal sürecinde"},
  de:{land:"Grundstück / Land",building:"Ganzes Gebäude",villa:"Haus / Villa",flat:"Wohnung",commercial:"Gewerbe",other:"Sonstiges",single:"Alleineigentum",condo:"Wohnungseigentum",shared:"Miteigentum",transfer:"Umschreibung / Erbe läuft",unknown:"Nicht bekannt",zoned:"Baurecht vorhanden",unzoned:"Landwirtschaft / ohne Baurecht",plan:"Planung / Transformation",soon:"Zeitnah bei passendem Angebot",month:"7–30 Tage",quarter:"1–3 Monate",later:"Später",sole:"Alleineigentümer",joint:"Gemeinsame Entscheidung möglich",nojoint:"Miteigentümer, noch keine Einigung",inherit:"Erbe / Umschreibung läuft"},
  en:{land:"Land / plot",building:"Whole building",villa:"House / villa",flat:"Apartment",commercial:"Commercial",other:"Other",single:"Single owner",condo:"Condominium title",shared:"Shared title",transfer:"Transfer / inheritance pending",unknown:"Not sure",zoned:"Zoned / building rights",unzoned:"Agricultural / unzoned",plan:"Planning / redevelopment",soon:"Soon if terms are right",month:"7–30 days",quarter:"1–3 months",later:"Later",sole:"I am sole owner",joint:"Co-owners can decide together",nojoint:"Co-owner, no agreement yet",inherit:"Inheritance / transfer pending"},
  ru:{land:"Земля / участок",building:"Здание",villa:"Дом / вилла",flat:"Квартира",commercial:"Коммерческая",other:"Другое",single:"Один собственник",condo:"Кондоминиум",shared:"Долевая собственность",transfer:"Наследство / переоформление",unknown:"Не знаю",zoned:"Есть право застройки",unzoned:"Без застройки / сельхоз",plan:"Планирование / реконструкция",soon:"Быстро при подходящих условиях",month:"7–30 дней",quarter:"1–3 месяца",later:"Позже",sole:"Я единственный собственник",joint:"Совместное решение возможно",nojoint:"Нет общего решения",inherit:"Наследство / переоформление"},
  ar:{land:"أرض / قطعة",building:"مبنى كامل",villa:"منزل / فيلا",flat:"شقة",commercial:"تجاري",other:"أخرى",single:"مالك واحد",condo:"ملكية شقة",shared:"ملكية مشتركة",transfer:"إرث / نقل ملكية",unknown:"غير معروف",zoned:"حق بناء",unzoned:"زراعي / دون تنظيم",plan:"تخطيط / إعادة تطوير",soon:"قريباً إذا كانت الشروط مناسبة",month:"7–30 يوماً",quarter:"1–3 أشهر",later:"لاحقاً",sole:"أنا المالك الوحيد",joint:"قرار مشترك ممكن",nojoint:"لا يوجد قرار مشترك",inherit:"إرث / نقل ملكية"}
};

export const formOptions = Object.fromEntries(Object.entries(labels).map(([locale,l]:any)=>[locale,{
  types:[["Arsa / Tarla / Bahçe",l.land],["Bina",l.building],["Müstakil ev / Villa",l.villa],["Daire",l.flat],["Dükkan / Ticari",l.commercial],["Diğer",l.other]],
  titles:[["Müstakil tapu",l.single],["Kat mülkiyeti / kat irtifakı",l.condo],["Hisseli tapu",l.shared],["Tapu / intikal süreci devam ediyor",l.transfer],["Bilmiyorum",l.unknown]],
  zoning:[["İmarlı",l.zoned],["Tarla / imarsız",l.unzoned],["Plan / dönüşüm sürecinde",l.plan],["Bilmiyorum",l.unknown]],
  timing:[["Teklif uygunsa hemen",l.soon],["7-30 gün",l.month],["1-3 ay",l.quarter],["3+ ay",l.later]],
  decision:[["Tek malikim ve karar verebilirim",l.sole],["Diğer maliklerle birlikte karar verebiliriz",l.joint],["Hissedarıyım, henüz ortak karar yok",l.nojoint],["Miras / intikal sürecinde",l.inherit]]
}])) as Record<Locale,any>;
