export type Locale = "tr" | "de" | "en" | "ru" | "ar";
export const locales: Locale[] = ["tr", "de", "en", "ru", "ar"];
export const localizedLocales: Locale[] = ["de", "en", "ru", "ar"];

export const localeMeta: Record<Locale, {label:string;short:string;hreflang:string;dir:"ltr"|"rtl";path:string}> = {
  tr:{label:"Türkçe",short:"TR",hreflang:"tr-TR",dir:"ltr",path:"/"},
  de:{label:"Deutsch",short:"DE",hreflang:"de-DE",dir:"ltr",path:"/de"},
  en:{label:"English",short:"EN",hreflang:"en",dir:"ltr",path:"/en"},
  ru:{label:"Русский",short:"RU",hreflang:"ru",dir:"ltr",path:"/ru"},
  ar:{label:"العربية",short:"AR",hreflang:"ar",dir:"rtl",path:"/ar"},
};
export function localeFromPath(pathname:string):Locale { const s=pathname.split("/").filter(Boolean)[0]; return s && localizedLocales.includes(s as Locale) ? s as Locale : "tr"; }
export function localeHref(locale:Locale, hash=""){ const p=localeMeta[locale].path; return `${p}${hash}`; }

const regionsTR = [
  ["Beykoz","Riva • Ortaçeşme • Öğümce • Paşamandıra","Ana odak: arsa, eski yapı, villa ve müstakil yaşam."],
  ["Şile","Ağva • Ahmetli • Kabakoz","Kıyı, ikinci konut ve arsa odaklı dosyalar."],
  ["Çekmeköy / Ömerli","Ömerli • Reşadiye • Hüseyinli","Villa ve büyük parsel odaklı Anadolu yakası alternatifi."],
  ["Arnavutköy","Dursunköy • Tayakadın • Durusu","Altyapı hikâyesi güçlü; plan ve tapuda seçici yaklaşım."],
  ["Çatalca","İnceğiz • Subaşı • Kestanelik","Büyük parsel ve uzun vadeli arazi odağı."],
  ["Silivri / Büyükçekmece","Selimpaşa • Kavaklı • Gümüşyaka","Kıyı ve büyük parsellerde seçici değerlendirme."],
  ["Tuzla / Tepeören","Tepeören • Akfırat","Villa, ulaşım ve iş akslarının birleştiği bölge."],
  ["Sarıyer Kuzey","Zekeriyaköy • Uskumruköy • Kilyos","Premium, kıt ve fırsat bazlı dosyalar."],
];

export const copy: Record<Locale, any> = {
  tr:{
    metaTitle:"İstanbul’da Arsa, Ev ve Gayrimenkul Satışı | Emlak Alırım", metaDescription:"İstanbul’da arsa, ev, villa, bina veya hisseli gayrimenkul satmayı düşünüyorsanız gizli ön değerlendirme isteyin. Beykoz, Şile, Ömerli ve seçili bölgeler.",
    topbar:"İstanbul’da seçili bölgelerde yatırım odaklı gayrimenkul ön değerlendirmesi", nav:{regions:"Bölgeler",criteria:"Neleri değerlendiriyoruz?",guide:"Satış rehberi",cta:"Değerlendirme iste"},
    eyebrow:"İSTANBUL • ARSA • EV • BİNA", heroTitle:"Mülkünüzü satmayı mı düşünüyorsunuz?", heroEmphasis:"Önce sakin ve gizli biçimde değerlendirelim.", heroLead:"Arsa, ev, villa veya binanızın konum ve temel bilgilerini paylaşın. Yatırım kriterlerimize uyarsa sizinle doğrudan görüşelim.",
    trust:["Gizli ön değerlendirme","İlan vermek zorunda değilsiniz","Tapu ve imar bilgisine bakıyoruz","Bağlayıcı olmayan ilk görüşme"], formTitle:"Mülkünüzü değerlendirelim", formIntro:"Konum, mülk tipi, tapu ve satış planınızı paylaşın.",
    howTitle:"Önce dosyayı anlayalım, sonra seçenekleri konuşalım.", how:[["01","Bilgiyi gönderin","Konum, tür, m² ve satış planı ilk inceleme için yeterlidir."],["02","Ön inceleme","Tapu, imar, arsa payı, yapı ve bölge birlikte değerlendirilir."],["03","Görüşelim","Uygunsa detay, yerinde inceleme ve olası teklif koşulları konuşulur."]],
    regionsTitle:"Odaklandığımız bölgeler", regions:regionsTR,
    criteriaTitle:"İyi dosya her zaman kusursuz dosya değildir.", criteria:["Arsa ve büyük parsel","Eski bina ve güçlü arsa payı","Villa / müstakil ev","Miras, hisseli tapu veya kısa satış takvimi"],
    situationsTitle:"Satış nedeni farklı olabilir; süreç baskılı olmak zorunda değil.", situations:["Miras / intikal","Hisseli tapu","Boş veya eski yapı","Taşınma / portföy değişikliği"],
    faqTitle:"Sık sorulanlar", faq:[["İlan vermeden başvurabilir miyim?","Evet. İlk değerlendirme için açık ilan gerekmez."],["Hisseli tapu olabilir mi?","Evet. Pay yapısı ve diğer maliklerin durumu ayrıca incelenir."],["Ada/parsel bilmiyorsam?","Mahalle ve yaklaşık konumla başlayabilirsiniz."],["Başvuru satış zorunluluğu doğurur mu?","Hayır. Ön değerlendirme bağlayıcı değildir."]],
    finalTitle:"Satış fikriniz varsa, önce dosyayı konuşalım.", finalButton:"Mülkümü değerlendirin", guideCta:"Satış rehberlerini incele", privacyTitle:"KVKK ve veri kullanımı", privacyText:"Bilgiler yalnızca başvurunuza yanıt vermek ve taşınmazı ön değerlendirmek amacıyla kullanılmalıdır."
  },
  de:{
    metaTitle:"Immobilie oder Grundstück in Istanbul verkaufen | Emlak Alırım", metaDescription:"Diskrete Vorprüfung für Eigentümer, die Grundstück, Haus, Villa oder Gebäude in Istanbul verkaufen möchten.", topbar:"Diskrete Immobilien-Vorprüfung in ausgewählten Lagen Istanbuls", nav:{regions:"Regionen",criteria:"Was wir prüfen",guide:"Ratgeber",cta:"Prüfung anfragen"},
    eyebrow:"ISTANBUL • GRUNDSTÜCK • HAUS • GEBÄUDE", heroTitle:"Sie denken über einen Verkauf nach?", heroEmphasis:"Wir prüfen die Immobilie zunächst diskret.", heroLead:"Senden Sie Lage und Eckdaten. Passt das Objekt zu unseren Anlagekriterien, sprechen wir direkt mit Ihnen.", trust:["Diskrete Prüfung","Keine öffentliche Anzeige nötig","Tapu/Baurecht wird berücksichtigt","Unverbindlicher Erstkontakt"], formTitle:"Immobilie prüfen lassen", formIntro:"Lage, Objektart, Eigentum und Verkaufsplan reichen für den Start.",
    howTitle:"Erst verstehen, dann entscheiden.", how:[["01","Daten senden","Lage, Typ und Größe angeben."],["02","Prüfung","Eigentum, Baurecht und Lage werden eingeordnet."],["03","Direktes Gespräch","Bei passender Gelegenheit besprechen wir Details."]], regionsTitle:"Ausgewählte Regionen", regions:regionsTR,
    criteriaTitle:"Interessant sind nicht nur perfekte Objekte.", criteria:["Grundstücke und größere Parzellen","Ältere Gebäude mit Grundstückswert","Villen und freistehende Häuser","Erbe, Miteigentum oder Leerstand"], situationsTitle:"Auch besondere Verkaufssituationen sind möglich.", situations:["Erbe","Miteigentum","Leerstand / ältere Immobilie","Umzug / Portfolioänderung"],
    faqTitle:"Häufige Fragen", faq:[["Muss ich die Immobilie inserieren?","Nein."],["Ist Miteigentum möglich?","Ja, die Eigentumsstruktur wird separat geprüft."],["Kann ich aus Deutschland verkaufen?","Die erste Prüfung kann vollständig online starten."],["Ist die Anfrage verbindlich?","Nein."]], finalTitle:"Wenn Sie über einen Verkauf nachdenken, beginnen wir mit den Eckdaten.", finalButton:"Prüfung anfragen", guideCta:"Türkische Verkaufsratgeber", privacyTitle:"Datenschutz", privacyText:"Ihre Angaben werden zur Bearbeitung der Anfrage und Vorprüfung verwendet."
  },
  en:{
    metaTitle:"Sell Property or Land in Istanbul | Emlak Alırım", metaDescription:"Private initial review for owners considering selling land, a house, villa or building in Istanbul.", topbar:"Private property review in selected Istanbul locations", nav:{regions:"Areas",criteria:"What we review",guide:"Guide",cta:"Request review"}, eyebrow:"ISTANBUL • LAND • HOUSE • BUILDING", heroTitle:"Thinking about selling a property?", heroEmphasis:"Start with a private review.", heroLead:"Share the location and key facts. If the property fits our investment criteria, we can speak directly.", trust:["Private review","No public listing required","Title and zoning considered","No-obligation first contact"], formTitle:"Request a property review", formIntro:"Location, type, ownership and timing are enough to start.", howTitle:"Understand the property first.", how:[["01","Send details","Location, type and size."],["02","Initial review","Title, zoning and location are assessed."],["03","Direct conversation","If relevant, we discuss the next steps."]], regionsTitle:"Selected focus areas", regions:regionsTR, criteriaTitle:"A good opportunity does not have to be perfect.", criteria:["Land and larger plots","Older buildings with land value","Villas and detached homes","Inheritance, shared title or vacancy"], situationsTitle:"Different selling situations are welcome.", situations:["Inheritance","Shared ownership","Vacant / older property","Relocation / portfolio change"], faqTitle:"FAQ", faq:[["Do I need to list publicly?","No."],["Can shared-title property be reviewed?","Yes."],["Can I start from abroad?","Yes, the initial review can be remote."],["Is the enquiry binding?","No."]], finalTitle:"If selling is on your mind, start with the facts.", finalButton:"Request review", guideCta:"View Turkish seller guides", privacyTitle:"Privacy", privacyText:"Your details are used to respond to your enquiry and review the property."
  },
  ru:{
    metaTitle:"Продать недвижимость или землю в Стамбуле | Emlak Alırım", metaDescription:"Конфиденциальная первичная оценка земли, дома, виллы или здания в Стамбуле.", topbar:"Конфиденциальная оценка недвижимости в Стамбуле", nav:{regions:"Районы",criteria:"Что рассматриваем",guide:"Гид",cta:"Запросить оценку"}, eyebrow:"СТАМБУЛ • ЗЕМЛЯ • ДОМ • ЗДАНИЕ", heroTitle:"Думаете о продаже недвижимости?", heroEmphasis:"Начните с конфиденциальной оценки.", heroLead:"Сообщите район и основные параметры. Если объект подходит нашим инвестиционным критериям, обсудим его напрямую.", trust:["Конфиденциально","Публичное объявление не обязательно","Проверяем Tapu и зонирование","Без обязательств"], formTitle:"Отправить объект на оценку", formIntro:"Район, тип, собственность и сроки — достаточно для начала.", howTitle:"Сначала понять объект.", how:[["01","Данные","Район, тип и площадь."],["02","Оценка","Документы, зонирование и локация."],["03","Контакт","Если интересно — обсуждаем детали."]], regionsTitle:"Основные районы", regions:regionsTR, criteriaTitle:"Интересны не только идеальные объекты.", criteria:["Земля и крупные участки","Старые здания с ценностью земли","Виллы и отдельные дома","Наследство или долевая собственность"], situationsTitle:"Можно обратиться и в нестандартной ситуации.", situations:["Наследство","Долевая собственность","Пустующий объект","Переезд"], faqTitle:"Вопросы", faq:[["Нужно ли публиковать объявление?","Нет."],["Можно ли с долевой собственностью?","Да."],["Можно начать из-за границы?","Да."],["Заявка обязательна?","Нет."]], finalTitle:"Если думаете о продаже — начните с основных данных.", finalButton:"Запросить оценку", guideCta:"Турецкие руководства", privacyTitle:"Конфиденциальность", privacyText:"Данные используются для ответа на запрос и первичной оценки объекта."
  },
  ar:{
    metaTitle:"بيع عقار أو أرض في إسطنبول | Emlak Alırım", metaDescription:"تقييم أولي وسري للمالكين الراغبين في بيع أرض أو منزل أو فيلا أو مبنى في إسطنبول.", topbar:"تقييم عقاري سري في مناطق مختارة من إسطنبول", nav:{regions:"المناطق",criteria:"ما نراجعه",guide:"الدليل",cta:"اطلب التقييم"}, eyebrow:"إسطنبول • أرض • منزل • مبنى", heroTitle:"هل تفكر في بيع عقارك؟", heroEmphasis:"ابدأ بتقييم أولي وسري.", heroLead:"أرسل الموقع والمعلومات الأساسية. إذا كان العقار مناسباً لمعاييرنا الاستثمارية نتواصل معك مباشرة.", trust:["تقييم سري","لا حاجة لإعلان عام","مراجعة سند الملكية والتنظيم","تواصل أولي غير ملزم"], formTitle:"اطلب تقييماً للعقار", formIntro:"الموقع والنوع والملكية والمدة تكفي للبدء.", howTitle:"نفهم العقار أولاً.", how:[["01","أرسل البيانات","الموقع والنوع والمساحة."],["02","مراجعة أولية","السند والتنظيم والموقع."],["03","تواصل مباشر","إذا كان مناسباً نناقش التفاصيل."]], regionsTitle:"مناطق التركيز", regions:regionsTR, criteriaTitle:"الفرصة الجيدة لا يجب أن تكون مثالية.", criteria:["أراضٍ وقطع كبيرة","مبانٍ قديمة بقيمة أرض قوية","فلل ومنازل مستقلة","إرث أو ملكية مشتركة"], situationsTitle:"يمكن التواصل في حالات بيع مختلفة.", situations:["إرث","ملكية مشتركة","عقار شاغر أو قديم","انتقال أو تغيير المحفظة"], faqTitle:"أسئلة شائعة", faq:[["هل يجب نشر إعلان؟","لا."],["هل تقبل الملكية المشتركة؟","نعم، تتم مراجعتها بشكل منفصل."],["هل يمكن البدء من الخارج؟","نعم."],["هل الطلب ملزم؟","لا."]], finalTitle:"إذا كنت تفكر في البيع، ابدأ بالمعلومات الأساسية.", finalButton:"اطلب التقييم", guideCta:"أدلة البائعين باللغة التركية", privacyTitle:"الخصوصية", privacyText:"تستخدم البيانات للرد على طلبك وإجراء التقييم الأولي."
  }
};
